### ISSUE TITLE
Run tests

### ISSUE THREAD

**Issue by wanggsz** [acforvs/po-mapf-thesis#1]
Hi, 
Thank you so much for your work! It's of great help. 

I have some problems regarding testing models. I notice there're codes for test, but I don't know where to run them. I wonder if you could help me with it. Thanks a lot!!

**Comment by acforvs** [comment]
Hi @wanggsz, thanks! 

To evaluate the final performance, please use the `test_model` function in the evaluate.py script located at `pathfinding/models/dhc/`. 

The script supports the `fire` library for command-line arguments, which means that you can run something similar to `poetry run python3 pathfinding/models/dhc/evaluate.py test_model '[(40, 4, 0.1), (80, 4, 0.1), (40, 8, 0.1), (80, 8, 0.1), (40, 16, 0.1), (80, 16, 0.1), (40, 32, 0.1), (80, 32, 0.1),  (40, 4, 0.3), (80, 4, 0.3),  (40, 8, 0.3), (80, 8, 0.3),  (40, 16, 0.3), (80, 16, 0.3), (40, 32, 0.3), (80, 32, 0.3)]' 337500` to test the model with the provided id (337500  in this example; weights must be located in the /models dir) on a set of provided maps.

You can append a True/False flag at the end of the command to choose between MovingAI maps and regular random maps from the original paper. For MovingAI maps, the command would be something like `poetry run python3 pathfinding/models/dhc/evaluate.py test_model '[(32, "Berlin_0_256.map", "Berlin_0_256.map.scen")]' 337500 False`

There's also a function to visualize the performance on a single map instance: https://github.com/acforvs/dhc-robust-mapf/blob/main/pathfinding/models/dhc/visualize.py#L64 for random maps and https://github.com/acforvs/dhc-robust-mapf/blob/main/pathfinding/models/dhc/visualize.py#L133 for MovingAI maps
